Lesson 7
ozoncp/ocp-course-api pull request #5
Opened 2021-06-14 18:26 UTC by ashashev

2021-06-17 15:11 UTC, zuzmic requested changes

2021-06-17 15:11 UTC, zuzmic commented on cmd/ocp-course-api/main.go
> +	}
а почему не сразу ? 

```go
defConfig, err := uc.LoadDefault()
if  err != nil {
	log.Fatal().Err(err).Msg("Couldn't read config")
}

log.Info().Msgf("read config:\n%v\n", defConfig)
```

2021-06-17 15:11 UTC, zuzmic commented on cmd/ocp-course-api/main.go
> +	}
то же самое что и чуть выше
можно сразу прочитать в serverConfig

2021-06-17 15:11 UTC, zuzmic commented on cmd/ocp-course-api/main.go
> +	if len(dsn) == 0 {
так немного читабельнее
```
if dsn == ""
```

2021-06-17 15:11 UTC, zuzmic commented on cmd/ocp-course-api/main.go
> +	ctxTerminated, stop2 := signal.NotifyContext(ctxInterrupted, syscall.SIGTERM)
не совсем понял эту историю с двумя контекстами 
так разве нельзя ?

```
	ctxInterrupted, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
```

2021-06-17 15:11 UTC, zuzmic commented on cmd/ocp-course-api/main.go
> +		log.Error().Err(err).Msg("Couldn't connect to DB")
можно заменить на log.Fatal() для однообразия

2021-06-17 15:11 UTC, zuzmic commented on cmd/ocp-lesson-api/main.go
>  import (
те же самые комментарии что и к файлу выше

2021-06-17 15:11 UTC, zuzmic commented on cmd/utils-demo/main.go
>  import (
а этот файл вообще нужен ?

2021-06-17 15:11 UTC, zuzmic commented on cmd/ocp-lesson-api/main.go
> +		log.Info().Err(err)
log.Error() ?

2021-06-17 15:11 UTC, zuzmic commented on internal/api/config.go
> +		return
return nil, err

2021-06-17 15:11 UTC, zuzmic commented on internal/api/config.go
> +func (c *ListenConfig) Validate() error {
Эта функция точно нужна?
почему не отдать это на откуп listen функции, 
уверен что она под капотом все это проверяет

2021-06-17 15:11 UTC, zuzmic commented on internal/api/ocp-course-api.go
> +	repo repo.RepoModelCourse
можешь резделить поля и  embeded ? 
```
type ocpCourseApiServer struct {
	pb.UnimplementedOcpCourseApiServer
	
	repo repo.RepoModelCourse
}
```

2021-06-17 15:11 UTC, zuzmic commented on internal/api/ocp-lesson-api.go
> +	repo repo.RepoModelLesson
тут тоже

2021-06-17 15:11 UTC, zuzmic commented on internal/repo/impl/repo_course.go
> +type rowCourse struct {
вообще я такое редко вижу, 
тут model.Cource - лишняя абстракция,

можно просто заменить на структуру с экспортируемыми  полями

2021-06-17 15:11 UTC, zuzmic commented on internal/utils/utils.go
>  func ToMapCourse(xs []model.Course) map[uint64]model.Course {
кажется что все эти функции не используются,
давай выпилим их ?

2021-06-18 09:54 UTC, ashashev commented on cmd/ocp-course-api/main.go
> +		log.Error().Err(err).Msg("Couldn't connect to DB")
Насколько я понял, в этом случае не вызовутся отложенные функции. В целом всё равно, так мы уже завершаем работу приложения, но вдруг там будет какой полезный defer. Я в следующем PR переделал это и не использую log.Fatal нигде.

2021-06-18 10:25 UTC, ashashev commented on internal/api/config.go
> +func (c *ListenConfig) Validate() error {
Так или иначе, но вернет ошибку, если эти параметры не валидные. В том числе, если отсутвует интерфейс который мы хотим слушать или указаный порт занят. Но хочется проверять наличие файла с описанием свагера. А если всё равно проверять, то чтобы сразу и не проверить и остальные поля?

2021-06-18 10:35 UTC, ashashev commented on internal/repo/impl/repo_course.go
> +type rowCourse struct {
Интерфейс репозиторий генерировался для model.Course/model.Lesson. Заставить сгенерировать эти интерфейсы  для типов которые сгенерировались из протобафа нормально у меня не получилось. Алиасы в genny не подсунуть, а имя интрфейса вида RepoOcp_course_apiCourse мне не нравится. Плюс я еще надеялся, что воспользуюсь Flusher, но не сложилось.
Но выносить на уровень интерфейса внутреннее представление данный, то как они в таблице лежат тоже не хочется. Мало ли как мне захочется их по полям таблицы раскладывать. Может захочется взять не постгресс, и там будет другой вид для rowCourse.

2021-06-18 10:36 UTC, ashashev commented on internal/utils/utils.go
>  func ToMapCourse(xs []model.Course) map[uint64]model.Course {
Обязательно, как раз собрался это сделать, но мгу и в рамках работы над этим PR выкинуть всё что по итогу оказалось не нужным.

2021-06-18 12:48 UTC, ashashev commented on cmd/ocp-course-api/main.go
> +	}
поправил

2021-06-18 12:49 UTC, ashashev commented on cmd/ocp-course-api/main.go
> +	}
поправил

2021-06-18 12:49 UTC, ashashev commented on cmd/ocp-course-api/main.go
> +	if len(dsn) == 0 {
поправил

2021-06-18 12:49 UTC, ashashev commented on cmd/ocp-course-api/main.go
> +	ctxTerminated, stop2 := signal.NotifyContext(ctxInterrupted, syscall.SIGTERM)
проглядел, что принимает список сигналов.
поправил

2021-06-18 12:49 UTC, ashashev commented on cmd/ocp-lesson-api/main.go
>  import (
поправил

2021-06-18 12:50 UTC, ashashev commented on cmd/utils-demo/main.go
>  import (
убрал

2021-06-18 12:50 UTC, ashashev commented on cmd/ocp-lesson-api/main.go
> +		log.Info().Err(err)
поправил

2021-06-18 12:50 UTC, ashashev commented on internal/api/config.go
> +		return
поправил

2021-06-18 12:50 UTC, ashashev commented on internal/api/ocp-course-api.go
> +	repo repo.RepoModelCourse
сделал

2021-06-18 12:50 UTC, ashashev commented on internal/api/ocp-lesson-api.go
> +	repo repo.RepoModelLesson
сделал

2021-06-18 12:50 UTC, ashashev commented on internal/utils/utils.go
>  func ToMapCourse(xs []model.Course) map[uint64]model.Course {
выкинул всё не используемое

2021-06-18 15:30 UTC, zuzmic commented on cmd/ocp-course-api/main.go
> +		log.Error().Err(err).Msg("Couldn't connect to DB")
да, ты прав, давай оставим как есть

2021-06-18 15:34 UTC, zuzmic commented on internal/api/config.go
> +func (c *ListenConfig) Validate() error {
ок, давай оставим

2021-06-18 15:37 UTC, zuzmic approved these changes

2021-06-18 15:37 UTC, merged